apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ include "next-public-website.fullname" . }}
  {{- if .Values.gitlab.enabled }}
  annotations:
    {{- include "next-public-website.gitlab-annotations" . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "next-public-website.labels" . | nindent 4 }}
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: {{ include "next-public-website.fullname" . }}-ingress-cert
      hosts:
        - {{ .Values.ingress.host | quote }}
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - {{ .Values.ingress.host | quote }}
      tls:
        httpsRedirect: false