apiVersion: v1
kind: Service
metadata:
  name: {{ include "next-public-website.fullname" . }}
  {{- if .Values.gitlab.enabled }}
  annotations:
    {{- include "next-public-website.gitlab-annotations" . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "next-public-website.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http-ingress
      protocol: TCP
      name: http
  selector:
    {{- include "next-public-website.selectorLabels" . | nindent 4 }}
