# Default values for next-public-website.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: registry.gitlab.com/atomix/next-atomix-website
  pullPolicy: IfNotPresent
  tag: v1

imagePullSecrets:
  - name: gitlab-registry
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

gitlab:
  enabled: true
  app: <replace_me>
  env: <replace_me>

ingress:
  host: atomix.k8s.atomix.dev

resources:
   limits:
     cpu: 250m
     memory: 512Mi
   requests:
     cpu: 100m
     memory: 256Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

auth:
  enabled: true
  username: atomix
  password: atomix